# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Study-Ship' do
	pod 'YYWebImage'
	pod 'SVProgressHUD'
	pod 'AFNetworking'
	pod 'pop'
	pod 'Masonry'
	pod 'MJRefresh'
end